### ISSUE TITLE
[Bug] Blank Screen

### ISSUE THREAD

**Issue by Ed1ks** [mpsxdeveloper/primevue-cdn-test#1]
Hello,
The HTML Skript results in a blank screen.

![image](https://github.com/mpsxdeveloper/primevue-cdn-test/assets/46250296/4468274a-d35f-4a1c-8ad1-f5aa553e5183)

**Comment by mpsxdeveloper** [comment]
I have changed the script tag to update the CDN for VueJS, so this error has been fixed. However, the VueJS code had some warning messages, so I have built a new branch with some improvements.
